spring.application.name=cyclix-api
server.port=${SERVER_PORT:6060}
spring.flyway.validate-migration-naming=true
app.jwt.secret=cyclix-local-dev-secret-change-me-please-123456
app.jwt.expiration-seconds=86400
spring.docker.compose.enabled=false
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/DB_cyclix}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cyclix_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cyclix10}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
